### ISSUE TITLE
Issue running the server.

### ISSUE THREAD

**Issue by maniappan** [JanGorman/jersey-passbook#1]
Hi Jan,
I got the maven run and the jar file is created successfully. I run the jar and get the exception that com/passbook/core/HstoreUserType.class is not getting instantiated, however I see that present in the jar file. Is there anyother thing I need to check on why it is not showing up in classpath?.
Error Trace :
mani@mani-laptop:~/passbookserver/jersey-passbook-master$ java -jar target/jersey-passbook-1.0.jar server service-configuration.yml
INFO  [2015-05-12 07:50:13,468] org.hibernate.annotations.common.Version: HCANN000001: Hibernate Commons Annotations {4.0.1.Final}
INFO  [2015-05-12 07:50:13,476] org.hibernate.Version: HHH000412: Hibernate Core {4.1.9.Final}
INFO  [2015-05-12 07:50:13,477] org.hibernate.cfg.Environment: HHH000206: hibernate.properties not found
INFO  [2015-05-12 07:50:13,479] org.hibernate.cfg.Environment: HHH000021: Bytecode provider name : javassist
INFO  [2015-05-12 07:50:13,504] com.yammer.dropwizard.hibernate.SessionFactoryFactory: Entity classes: [com.passbook.core.Device, com.passbook.core.Registration]
Exception in thread "main" org.hibernate.MappingException: Unable to instantiate custom type: com.passbook.core.HstoreUserType
	at org.hibernate.type.TypeFactory.custom(TypeFactory.java:218)
	at org.hibernate.type.TypeFactory.custom(TypeFactory.java:204)
	at org.hibernate.type.TypeFactory.byClass(TypeFactory.java:103)
	at org.hibernate.type.TypeResolver.heuristicType(TypeResolver.java:130)
	at org.hibernate.mapping.SimpleValue.getType(SimpleValue.java:305)
	at org.hibernate.mapping.SimpleValue.isValid(SimpleValue.java:292)
	at org.hibernate.mapping.Property.isValid(Property.java:239)
	at org.hibernate.mapping.PersistentClass.validate(PersistentClass.java:469)
	at org.hibernate.mapping.RootClass.validate(RootClass.java:270)
	at org.hibernate.cfg.Configuration.validate(Configuration.java:1294)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1742)
	at com.yammer.dropwizard.hibernate.SessionFactoryFactory.buildSessionFactory(SessionFactoryFactory.java:77)
	at com.yammer.dropwizard.hibernate.SessionFactoryFactory.build(SessionFactoryFactory.java:35)
	at com.yammer.dropwizard.hibernate.HibernateBundle.run(HibernateBundle.java:38)
	at com.yammer.dropwizard.hibernate.HibernateBundle.run(HibernateBundle.java:13)
	at com.yammer.dropwizard.config.Bootstrap.runWithBundles(Bootstrap.java:64)
	at com.yammer.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:37)
	at com.yammer.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:58)
	at com.yammer.dropwizard.cli.Cli.run(Cli.java:53)
	at com.yammer.dropwizard.Service.run(Service.java:61)
	at com.passbook.PassbookService.main(PassbookService.java:28)
Caused by: java.lang.IllegalAccessException: Class org.hibernate.type.TypeFactory can not access a member of class com.passbook.core.HstoreUserType with modifiers ""
	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:101)
	at java.lang.Class.newInstance(Class.java:432)
	at org.hibernate.type.TypeFactory.custom(TypeFactory.java:213)
	... 20 more

**Comment by maniappan** [comment]
Happens for both Java 7 and 8, the class file is present in the com/passbook/core and is compiled properly, looks like the Device and Registration classes have been loaded properly, only this extension type is having issue to load, other two I see are proper tables.

**Comment by JanGorman** [comment]
@maniappan Interesting that… Just back from vacation today, I'll have a look tomorrow

**Comment by maniappan** [comment]
OS: Ubuntu 14.04, DB: Postgresql 9.3 on localhost.

Date: Tue, 12 May 2015 09:15:14 -0700

**Comment by maniappan** [comment]
Thanks, works good.

Date: Wed, 13 May 2015 10:27:49 -0700
